LEAGUE_NAME = 'East Bay Senior Soccer League'
LEAGUE_NAME_SHORT = 'EBSSL'
REGISTRAR_EMAIL = 'bluestango@gmail.com'
STATE_ABBREVS = {
  "Alabama" => "AL",
  "Alaska" => "AK",
  "Arizona" => "AZ",
  "Arkansas" => "AR",
  "California" => "CA",
  "Colorado" => "CO",
  "Connecticut" => "CT",
  "Delaware" => "DE",
  "Florida" => "FL",
  "Georgia" => "GA",
  "Hawaii" => "HI",
  "Idaho" => "ID",
  "Illinois" => "IL",
  "Indiana" => "IN",
  "Iowa" => "IA",
  "Kansas" => "KS",
  "Kentucky" => "KY",
  "Louisiana" => "LA",
  "Maine" => "ME",
  "Maryland" => "MD",
  "Massachusetts" => "MA",
  "Michigan" => "MI",
  "Minnesota" => "MN",
  "Mississippi" => "MS",
  "Missouri" => "MO",
  "Montana" => "MT",
  "Nebraska" => "NE",
  "Nevada" => "NV",
  "New Hampshire" => "NH",
  "New Jersey" => "NJ",
  "New Mexico" => "NM",
  "New York" => "NY",
  "North Carolina" => "NC",
  "North Dakota" => "ND",
  "Ohio" => "OH",
  "Oklahoma" => "OK",
  "Oregon" => "OR",
  "Pennsylvania" => "PA",
  "Rhode Island" => "RI",
  "South Carolina" => "SC",
  "South Dakota" => "SD",
  "Tennessee" => "TN",
  "Texas" => "TX",
  "Utah" => "UT",
  "Vermont" => "VT",
  "Virginia" => "VA",
  "Washington" => "WA",
  "West Virginia" => "WV",
  "Wisconsin" => "WI",
  "Wyoming" => "WY"
}
POSITIONS_4231 = [
  ["Sub", 0],
  ["#1 (GK)", 1],
  ["#2 (RWB)", 2],
  ["#3 (LWB)", 3],
  ["#4 (CB)", 4],
  ["#5 (CB)", 5],
  ["#6 (DM)", 6],
  ["#7 (RAM)", 7],
  ["#8 (DM)", 8],
  ["#9 (S)", 9],
  ["#10 (CAM)", 10],
  ["#11 (LAM)", 11]
]
POSITION_COLORS = {
  GK: '#aaaaaa',
  CB: 'cyan',
  WB: '#aaffaa',
  LWB: '#aaffaa',
  RWB: '#aaffaa',
  DM: 'yellow',
  AM: 'orange',
  RAM: 'orange',
  LAM: 'orange',
  CAM: '#ffaa66',
  S: '#ffaaaa'
}