development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: soccer_development
  pool:     5
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: soccer_test
  pool:     5
  template: template0
